### ISSUE TITLE
example's cpu usage is very high

### ISSUE THREAD

**Issue by whisper-bye** [eliemichel/glfw3webgpu#1]
Such as the title

os: macOS 13.1
arch: m1 pro

<img width="532" alt="image" src="https://user-images.githubusercontent.com/3895096/227824365-80d8b764-49f4-4bcf-b0dd-50ec0be2ae7a.png">

**Comment by eliemichel** [comment]
Is it still the case when removing the WebGPU related part of the code? Try something like this:

```C
#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>
#include <stdio.h>

int main(int, char*[]) {
	// Init GLFW
	glfwInit();
	glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);
	GLFWwindow* window = glfwCreateWindow(640, 480, "Learn WebGPU", NULL, NULL);

	while (!glfwWindowShouldClose(window)) glfwPollEvents();

	// Terminate GLFW
	glfwDestroyWindow(window);
	glfwTerminate();

	return 0;
}
```

**Comment by whisper-bye** [comment]
same result with 100% cpu

**Comment by eliemichel** [comment]
The issue is not related to this repo then. The reason actually is that the infinite loop does nothing, in particular it does not _**present**_ anything on screen, which is the operation that would limit it to e.g., 60 iterations per second in a real application.

Just remove the main loop if you have no use for it. ;)
